services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: challenge
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pdev"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: demo-app
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/challenge?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dev
      SPRING_DATASOURCE_WRITER_URL: jdbc:mysql://mysql:3306/challenge?createDatabaseIfNotExist=true
