replicaCount: 1

image:
  repository: demo-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 8080

resources: {}

autoscaling:
  enabled: false

serviceAccount:
  create: false

ingress:
  enabled: false

httpRoute:
  enabled: false